name: Workflow Runners

on: push

jobs:
    ubuntu-echo:
      runs-on:  ubuntu-latest
      steps:
          - name: Show OS
            run: |
              echo "This is running on an ubuntu runner"
              echo "Runner OS: $RUNNER_OS"
              echo "My name is Mahavir Saroj-maha"